name: ESLint CI and Codacy code quality check 

on: 
  push:
    paths:
      - '**.js'
    branches-ignore:
      - 'master'

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 12
    
      - name: Install modules
        run: npm ci
        
      - name: Run linter
        run: npm run lint
  
  codacy-analysis-cli:

    needs: lint
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI (JS)
        uses: codacy/codacy-analysis-cli-action@master
        with:
          directory: source/js
      
      - name: Run Codacy Analysis CLI (SCSS)
        uses: codacy/codacy-analysis-cli-action@master
        with:
          directory: source/scss
